### ISSUE TITLE
AZURE_SDK_GO_OMIT_READONLY not work after remove json tag

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#1004]
Introduced in this PR: https://github.com/Azure/autorest.go/pull/941. A simple workaround is we still generate it when the property is read only.

**Comment by jhendrixMSFT** [comment]
For some history, we used to omit sending R/O fields by default.  This behavior was later removed on 2022-10-07, and we added `AZURE_SDK_GO_OMIT_READONLY` as an escape hatch in case some services were misbehaving.  Since we haven't seen any bug reports, I'm inclined to say we leave this as is and remove the R/O fields omission code from `azcore`.  @JeffreyRichter thoughts on this?

**Comment by jhendrixMSFT** [comment]
The dead code has been removed from `azcore`.
