### ISSUE TITLE
Incorrect client name

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1222]
typespec: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurelargeinstance/AzureLargeInstance.Management

xxx_client.go has a prefix: `azurelargeinstance`
![image](https://github.com/Azure/autorest.go/assets/46921893/aa79ba60-cf2c-4954-a304-7de6b347945c)

**Comment by jhendrixMSFT** [comment]
The stuttering cleanup won't rename this because the package suffix is `largeinstance` while the type name prefixes are `AzureLargeInstance`. I noticed this in internal testing as well. You'll need to use the `stutter` option to clean this up. See https://github.com/Azure/autorest.go/pull/1181/commits/c62ade3a1290f2a4d0047a862c743fce45fc77d4

**Comment by tadelesh** [comment]
Could workaround with `stutter` option.
