### ISSUE TITLE
Error: didn't find model type name OperationStatusResult for response envelope OperationStatusClientGetResponse

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1305]
typespec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceregistry/DeviceRegistry.Management/main.tsp#L76

![image](https://github.com/Azure/autorest.go/assets/46921893/f58de583-28d0-4d18-b4e5-7222e994599e)

**Comment by jhendrixMSFT** [comment]
This is due to over-aggressive removal of LRO status monitor types. For the tests currently checked in, they aren't used, but in this case they are. Note that in both cases the `usage` has them marked as output which seems like a bug. @tadelesh can this be fixed on the tcgc side? If not, we'll need to improve the detection logic.

**Comment by tadelesh** [comment]
I only saw it is used in response. Why `output` usage is wrong?

**Comment by jhendrixMSFT** [comment]
When building https://github.com/Azure/autorest.go/tree/main/packages/typespec-go/test/tsp/CodeSigning.Management

This includes a model `ArmOperationStatusResourceProvisioningState` with usage `Output`. However, none of the operations actually return an instance of this type. In this case, it would be ideal for `usage` to be `undefined` so it's clear that the type isn't actually used.

**Comment by jhendrixMSFT** [comment]
This will be fixed in `0.1.0-dev.3` of the emitter.

**Comment by tadelesh** [comment]
The tcgc usage issues should be fixed in this pr: https://github.com/Azure/typespec-azure/pull/826
