### ISSUE TITLE
Generated code has duplicate definition of clients

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.go#689]
To reproduce: https://github.com/Azure/azure-sdk-for-go/blob/78d2ffc460cdd605d8000ffba7426e070c394045/sdk/recoveryservices/armrecoveryservices/autorest.md
The generated code has two files with the same client definition:
![image](https://user-images.githubusercontent.com/10554446/132600495-44be1a1e-0e07-4f5c-94e1-1c7a812a8993.png)
Corresponding swagger links:
- https://github.com/Azure/azure-rest-api-specs/blob/e6851ee9d80a045e6d3e8f975fb2c59c3b7026e4/specification/recoveryservices/resource-manager/Microsoft.RecoveryServices/stable/2021-07-01/vaults.json#L129
- https://github.com/Azure/azure-rest-api-specs/blob/e6851ee9d80a045e6d3e8f975fb2c59c3b7026e4/specification/recoveryservices/resource-manager/Microsoft.RecoveryServices/stable/2021-07-01/vaults.json#L711

**Comment by jhendrixMSFT** [comment]
The problem here is that some operations don't define an operation group.  In this case, the code generator will use the value of the swagger title which in this case is "RecoveryServicesClient".  Unfortunately there are operations with the group name "RecoveryServices" which leads to the collision.

We could likely avoid this by slightly modifying the title to avoid duplicates, however I'm concerned that this might introduce versioning issues.  It might be preferred to use an autorest directive to fix the names so that it's consistent and not left to the whims of the current code generator (even better would be to fix the swagger but that's unlikely).

**Comment by jhendrixMSFT** [comment]
To close the loop, we should be using autorest directives to fix names.
