### ISSUE TITLE
Enum is sapce value

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#749]
## What happened?
- generator track2 adhybridhealthservice issue:
```
Error: Enum 'nextPartitionKey' cannot have a value ' ' that result in an empty name. Use x-ms-enum.values to specify the name of the values.
```
The enum of [nextPartitionKey and nextRowKey](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L459-L486) is a space string

**Comment by jhendrixMSFT** [comment]
The error is by design and comes from the Autorest front-end (i.e. this is not specific to Go).  The enum value names are generated from their values, and since these ones are spaces, no name can be generated.  You need to specify the values name as part of the `x-ms-enum` extension.  See the [docs](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-enum) for how to do that.
