### ISSUE TITLE
About removing read-only when marshaling

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#766]
We received an issue which prevent the customer to upgrade version because of removing read-only param when marshalling [here](https://github.com/Azure/azure-sdk-for-go/issues/16914). I know it is by designed both in track1 and track2. But if customer need to use marshalling for other purpose, it will cause some extra effort for the read-only prarams.

**Comment by jhendrixMSFT** [comment]
We solve removing of R/O fields in track 2 in a different way that doesn't impact the JSON marshaller.  Can the customer try track 2?

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT perhaps an odd take, but since this is ultimately a workaround for a series of API bugs (where fields which are readonly in the request should be being ignored, but instead return an error) are there any plans to fix the API's here too, which would remove the need for the workarounds in both Track1 and Track2?

**Comment by jhendrixMSFT** [comment]
The need to remove the R/O content was something new added to RPaaS, so it seems unlikely (I can look into it though).  This does bring up a point that that non RPaaS shouldn't have this restriction.  I will investigate that further too.

**Comment by jhendrixMSFT** [comment]
We won't be changing this for the legacy SDK.
